### ISSUE TITLE
Full installation instructions

### ISSUE THREAD

**Issue by brown7477** [alephmatic/full-stack-ai#2]
I was trying to install this to test it but the instructions are not helpful.
Please change the README to include full installation instructions to run the script.

**Comment by elie222** [comment]
This issue isn't helpful because it doesn't explain what problems you faced. The installation instructions are as shown in th README:

```md
export OPENAI_API_KEY=...
npx fsai gen "Build a clone of Twitter called StackPrompt where people prompt instead of tweet. Allow users to follow one another and to like prompts. Use GitHub for log in. Charge users a monthly fee for premium functionality."
```

Where `OPENAI_API_KEY` is something like `sk-xyz123`.

**Comment by elie222** [comment]
Closing till there's more info on the bug.
